/*
 * Global three hourly spot data
 *
 * This API provides three hourly weather forecast data for a requested coordinate defined by a latitude and longitude. The format of the data is GeoJSON.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: enquiries@metoffice.gov.uk
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParameterArray {
}

impl ParameterArray {
    pub fn new() -> ParameterArray {
        ParameterArray {
        }
    }
}


