/*
 * Global three hourly spot data
 *
 * This API provides three hourly weather forecast data for a requested coordinate defined by a latitude and longitude. The format of the data is GeoJSON.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: enquiries@metoffice.gov.uk
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Point {
    /// The longitude, latitude and elevation values for the point
    #[serde(rename = "coordinates")]
    pub coordinates: Vec<f32>,
    /// The GeoJSON type identifier
    #[serde(rename = "type")]
    pub r#type: String,
}

impl Point {
    pub fn new(coordinates: Vec<f32>, r#type: String) -> Point {
        Point {
            coordinates,
            r#type,
        }
    }
}


