/*
 * Global three hourly spot data
 *
 * This API provides three hourly weather forecast data for a requested coordinate defined by a latitude and longitude. The format of the data is GeoJSON.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: enquiries@metoffice.gov.uk
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Properties {
    /// The forecast location name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The distance from the requested point in metres
    #[serde(rename = "requestPointDistance")]
    pub request_point_distance: f32,
    /// The model run date in UTC
    #[serde(rename = "modelRunDate")]
    pub model_run_date: String,
    /// A time step ordered list  of forecast parameters and associated values
    #[serde(rename = "timeSeries")]
    pub time_series: Vec<crate::models::TimeSeries>,
}

impl Properties {
    pub fn new(request_point_distance: f32, model_run_date: String, time_series: Vec<crate::models::TimeSeries>) -> Properties {
        Properties {
            name: None,
            request_point_distance,
            model_run_date,
            time_series,
        }
    }
}


