/*
 * Global three hourly spot data
 *
 * This API provides three hourly weather forecast data for a requested coordinate defined by a latitude and longitude. The format of the data is GeoJSON.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: enquiries@metoffice.gov.uk
 * Generated by: https://openapi-generator.tech
 */

/// SpotForecastFeatureCollection : A feature collection object, must have a member array of features



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpotForecastFeatureCollection {
    /// The GeoJSON type identifier
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// A list of feature objects
    #[serde(rename = "features")]
    pub features: Vec<crate::models::Feature>,
    /// Forecast parameter metadata for all possible forecast parameters in response - each forecast parameter has a nested object containing a unit of measurement, using standard unit representation as defined by UCUM - http://unitsofmeasure.org/ucum.html - and an optional parameter definition
    #[serde(rename = "parameters")]
    pub parameters: Vec<crate::models::ParameterArray>,
}

impl SpotForecastFeatureCollection {
    /// A feature collection object, must have a member array of features
    pub fn new(features: Vec<crate::models::Feature>, parameters: Vec<crate::models::ParameterArray>) -> SpotForecastFeatureCollection {
        SpotForecastFeatureCollection {
            r#type: None,
            features,
            parameters,
        }
    }
}


