/*
 * Global three hourly spot data
 *
 * This API provides three hourly weather forecast data for a requested coordinate defined by a latitude and longitude. The format of the data is GeoJSON.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: enquiries@metoffice.gov.uk
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Unit {
    /// The name of the unit
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "symbol")]
    pub symbol: Box<crate::models::Symbol>,
}

impl Unit {
    pub fn new(label: String, symbol: crate::models::Symbol) -> Unit {
        Unit {
            label,
            symbol: Box::new(symbol),
        }
    }
}


